import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'sv' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  sv: {
    // LANDING
    'app.title': 'Sparkboard',
    'app.description': 'Sparkboard är en interaktiv plattform för kreativa workshops med sticky-notes och AI-analys',
    'app.tagline': 'Samarbeta, brainstorma och skapa tillsammans',
    'landing.facilitator.title': 'Facilitator',
    'landing.facilitator.description': 'Skapa och hantera workshops. Bjud in deltagare och få insikter i realtid.',
    'landing.facilitator.button': 'Skapa Workshop',
    'landing.participant.title': 'Deltagare',
    'landing.participant.description': 'Gå med i en workshop med din unika kod och dela dina idéer.',
    'landing.participant.button': 'Gå med i Workshop',
    
    // FEATURES
    'landing.features.realtime.title': 'Samarbeta i realtid',
    'landing.features.realtime.description': 'Se alla bidrag direkt när de skapas',
    'landing.features.easy.title': 'Enkel åtkomst',
    'landing.features.easy.description': 'Gå med via 6-siffrig kod eller QR - inget konto krävs',
    'landing.features.responsive.title': 'Responsiv design',
    'landing.features.responsive.description': 'Fungerar perfekt på mobil och desktop',
    'landing.features.ai.title': 'AI-analys',
    'landing.features.ai.description': 'Sammanfattar idéer, hittar teman och ger rekommendationer automatiskt',
    
    // AUTH & NAVIGATION
    'auth.login': 'Logga in',
    'auth.signup': 'Skapa konto',
    'auth.logout': 'Logga ut',
    'auth.myaccount': 'Mitt konto',
    'auth.email': 'E-post',
    'auth.password': 'Lösenord',
    'auth.company': 'Företagsnamn',
    'auth.facilitatorPin': 'Facilitator PIN',
    'auth.createPin': 'Skapa PIN',
    'auth.enterPin': 'Ange din PIN-kod',
    'auth.rememberMe': 'Kom ihåg mig',
    'auth.forgotPin': 'Glömt PIN?',
    'auth.register': 'Registrera',
    'auth.backToLogin': 'Tillbaka till inloggning',
    'auth.resetPin': 'Återställ PIN',
    'auth.resetSuccess': 'PIN återställd! Du kan nu logga in med din nya PIN.',
    'auth.resetError': 'Företaget hittades inte',
    'auth.loginSuccess': 'Välkommen tillbaka!',
    'auth.loginError': 'Felaktig PIN-kod',
    'auth.registerSuccess': 'Konto skapat! Du är nu inloggad.',
    'auth.registerError': 'Företagsnamnet används redan',
    'auth.loginTitle': 'Logga in',
    'auth.loginDescription': 'Logga in på ditt konto för att hantera workshops',
    'auth.name': 'Namn',
    'auth.pin': 'PIN-kod',
    'auth.loginButton': 'Logga in',
    'auth.createAccount': 'Skapa konto',
    'auth.or': 'eller',
    'auth.registerTitle': 'Skapa konto',
    'auth.registerDescription': 'Skapa ett nytt facilitatorkonto',
    'auth.nameOptional': 'Namn (valfritt)',
    'auth.nameOptionalPlaceholder': 'Ditt namn',
    'auth.confirmPin': 'Bekräfta PIN',
    'auth.securityInfo': 'Lägg till en säkerhetsfråga för att kunna återställa din PIN (valfritt)',
    'auth.securityQuestion': 'Säkerhetsfråga',
    'auth.securityQuestionPlaceholder': 'T.ex. Vad heter din första husdjur?',
    'auth.securityAnswer': 'Svar',
    'auth.securityAnswerPlaceholder': 'Ditt svar',
    'auth.cancel': 'Avbryt',
    'auth.createAccountButton': 'Skapa konto',
    'auth.pinMismatch': 'PIN-koderna matchar inte',
    'auth.pinMismatchDesc': 'Kontrollera att du angett samma PIN-kod två gånger',
    'auth.welcome': 'Välkommen!',
    'auth.welcomeDesc': 'Ditt konto har skapats',
    'auth.registerFailed': 'Kunde inte skapa konto',
    'auth.accountLocked': 'Kontot är låst',
    'auth.accountLockedDesc': 'För många misslyckade inloggningsförsök. Försök igen senare.',
    'auth.nameRequired': 'Namn krävs',
    'auth.nameRequiredDesc': 'Ange ditt namn för att logga in',
    'auth.accountNotFound': 'Kontot hittades inte',
    'auth.accountNotFoundDesc': 'Det finns inget konto med det namnet',
    'auth.loggedIn': 'Inloggad',
    'auth.welcomeBack': 'Välkommen tillbaka!',
    'auth.incorrectPin': 'Felaktig PIN-kod',
    'auth.attemptsLeft': '{count} försök kvar',
    'auth.accountNowLocked': 'Kontot är nu låst på grund av för många misslyckade försök',
    'auth.noAccountSelected': 'Inget konto valt',
    'auth.pinReset': 'PIN återställd',
    'auth.pinResetDesc': 'Du kan nu logga in med din nya PIN',
    'auth.resetFailed': 'Återställning misslyckades',
    'auth.resetPinTitle': 'Återställ PIN',
    'auth.resetPinDescription': 'Svara på din säkerhetsfråga för att återställa din PIN',
    'auth.securityQuestionLabel': 'Din säkerhetsfråga',
    'auth.yourAnswer': 'Ditt svar',
    'auth.yourAnswerPlaceholder': 'Ange ditt svar',
    'auth.newPin': 'Ny PIN',
    'auth.confirmNewPin': 'Bekräfta ny PIN',
    'auth.resetButton': 'Återställ PIN',
    'auth.pinPlaceholder': '••••••',
    'auth.namePlaceholder': 'Ditt namn',
    'auth.lockedOut': 'Kontot är låst på grund av för många misslyckade inloggningsförsök. Vänta 15 minuter.',
    'auth.attemptsRemaining': '{count} inloggningsförsök kvar',
    
    // CREATE WORKSHOP
    'workshop.create': 'Skapa Workshop',
    'workshop.new': 'Ny Workshop',
    'workshop.title': 'Titel',
    'workshop.titlePlaceholder': 'Min Workshop',
    'workshop.description': 'Beskrivning',
    'workshop.descriptionPlaceholder': 'Beskriv din workshop...',
    'workshop.addBoard': 'Lägg till Board',
    'workshop.boardTitle': 'Board-titel',
    'workshop.addQuestion': 'Lägg till Fråga',
    'workshop.questionText': 'Frågetext',
    'workshop.timeLimit': 'Tidsgräns (minuter)',
    'workshop.saveDraft': 'Spara som utkast',
    'workshop.activate': 'Aktivera Workshop',
    'workshop.update': 'Uppdatera Workshop',
    'workshop.code': 'Workshop-kod',
    'workshop.shareCode': 'Dela denna kod med deltagarna',
    'workshop.copyCode': 'Kopiera kod',
    'workshop.downloadQR': 'Ladda ner QR-kod',
    'workshop.boards': 'Boards',
    'workshop.maxBoards': 'Max 10 boards',
    'workshop.dragToReorder': 'Dra för att ändra ordning',
    'workshop.fillTitle': 'Fyll i en titel',
    'workshop.addAtLeastOneBoard': 'Lägg till minst ett board',
    'workshop.allBoardsNeedTitles': 'Alla boards behöver titlar',
    'workshop.allBoardsNeedQuestions': 'Alla boards behöver minst en fråga',
    
    // BOARD
    'boardCard.label': 'Board {index}',
    'boardCard.title': 'Titel',
    'boardCard.titlePlaceholder': 'Min Fråga',
    'boardCard.timeLimit': 'Tidsgräns (minuter)',
    'boardCard.questions': 'Frågor ({current}/{max})',
    'boardCard.questionPlaceholder': 'Fråga {index}',
    'boardCard.addQuestion': 'Lägg till fråga',
    
    // JOIN WORKSHOP
    'join.title': 'Gå med i Workshop',
    'join.welcome': 'Välkommen',
    'join.enterCode': 'Ange din 6-siffriga workshop-kod och ditt namn',
    'join.code': 'Workshop-kod',
    'join.codePlaceholder': '123456',
    'join.name': 'Ditt namn',
    'join.namePlaceholder': 'Anna Andersson',
    'join.button': 'Gå med i Workshop',
    'join.scanQR': 'Scanna QR-kod',
    'join.cancel': 'Avbryt',
    'join.getCodeFrom': 'Få workshop-koden från din facilitator',
    'join.joining': 'Ansluter...',
    'join.invalidCode': 'Ogiltig workshop-kod',
    'join.enterName': 'Ange ditt namn',
    'join.badge': 'Gå med',
    'join.connectTitle': 'Anslut till Workshop',
    'join.characters': '{count}/6 tecken',
    'join.infoTitle': 'Information',
    'join.infoCode': 'Koden består av 6 bokstäver och siffror',
    'join.infoNoAccount': 'Du behöver inte skapa ett konto för att delta',
    'join.infoNameVisible': 'Ditt namn kommer att visas för andra deltagare',
    'join.qrScanned': 'QR-kod scannad!',
    'join.qrCode': 'Workshop-kod: {code}',
    'join.cameraError': 'Kan inte starta kamera',
    'join.cameraPermission': 'Kontrollera att din webbläsare har tillgång till kameran',
    'join.welcomeToast': 'Välkommen!',
    'join.connectedTo': 'Du har anslutit till "{name}"',
    'join.connectionFailed': 'Kunde inte ansluta',
    'join.invalidCodeLength': 'Workshop-koden måste vara 6 tecken lång',
    'join.nameMissing': 'Namn saknas',
    'join.nameMinLength': 'Vänligen ange ett namn (minst 2 tecken)',
    'join.notFound': 'Workshop-koden hittades inte. Kontrollera att koden är korrekt.',
    'join.notActive': 'Denna workshop är inte aktiv just nu.',
    'join.limitReached': 'Workshopen har nått max antal deltagare.',
    'join.genericError': 'Något gick fel. Försök igen.',
    'join.scanQRTitle': 'Scanna QR-kod',
    'join.scanQRDescription': 'Rikta kameran mot QR-koden för att automatiskt fylla i workshop-koden',
    'join.scanQRHint': 'Se till att QR-koden är inom den gröna ramen',
    
    // WORKSHOP SESSION (PARTICIPANT)
    'session.workshop': 'Workshop',
    'session.timeRemaining': 'Tid kvar',
    'session.addNote': 'Lägg till anteckning',
    'session.yourNote': 'Din anteckning',
    'session.submit': 'Skicka',
    'session.notes': 'anteckningar',
    'session.noNotes': 'Inga anteckningar än',
    'session.waiting': 'Väntar på nästa board...',
    'session.currentBoard': 'Nuvarande board',
    
    // ADD NOTE
    'addNote.title': 'Lägg till anteckning',
    'addNote.description': 'Välj en fråga och skriv din anteckning',
    'addNote.selectQuestion': 'Välj fråga',
    'addNote.selectPlaceholder': 'Välj en fråga...',
    'addNote.noteContent': 'Anteckning',
    'addNote.notePlaceholder': 'Skriv din anteckning här...',
    'addNote.submit': 'Lägg till',
    'addNote.cancel': 'Avbryt',
    
    // NAVIGATION
    'nav.back': 'Tillbaka',
    'nav.login': 'Logga in',
    'nav.logout': 'Logga ut',
    'nav.myWorkshops': 'Mina Workshops',
    'nav.account': 'Konto',
    'nav.upgrade': 'Uppgradera',
    
    // FACILITATOR CONTROL
    'facilitator.control': 'Facilitator Control',
    'facilitator.workshop': 'Workshop',
    'control.title': 'Facilitator Control',
    'control.workshop': 'Workshop',
    'control.start': 'Start',
    'control.pause': 'Pausa',
    'control.resume': 'Fortsätt',
    'control.nextBoard': 'Next Board',
    'control.prevBoard': 'Previous Board',
    'control.aiAnalysis': 'AI Analysis',
    'control.exportPDF': 'Export PDF',
    'control.soundOn': 'Sound On',
    'control.soundOff': 'Sound Off',
    'control.hideControls': 'Dölj kontroller',
    'control.showControls': 'Visa kontroller',
    'control.hideParticipants': 'Dölj deltagare',
    'control.showParticipants': 'Visa deltagare',
    'facilitator.startTimer': 'Starta',
    'facilitator.pauseTimer': 'Pausa',
    'facilitator.nextBoard': 'Nästa Board',
    'facilitator.previousBoard': 'Föregående Board',
    'facilitator.aiAnalysis': 'AI-Analys',
    'facilitator.exportPDF': 'Exportera PDF',
    'facilitator.soundOn': 'Ljud På',
    'facilitator.soundOff': 'Ljud Av',
    'facilitator.participants': 'Deltagare',
    'facilitator.hideParticipants': 'Dölj deltagare',
    'facilitator.showParticipants': 'Visa deltagare',
    'facilitator.noParticipants': 'Inga deltagare ännu',
    'facilitator.board': 'Board',
    'facilitator.of': 'av',
    'facilitator.paused': 'Pausad',
    'facilitator.running': 'Körs',
    
    // PARTICIPANTS
    'participants.title': 'Deltagare ({count})',
    'participants.noParticipantsYet': 'Inga deltagare ännu',
    'participants.noParticipants': 'Inga deltagare ännu',
    'participants.deleteConfirm': 'Ta bort deltagare?',
    'participants.deleteConfirmDesc': 'Är du säker på att du vill ta bort {name}? Alla deras anteckningar kommer att raderas.',
    'participants.cancel': 'Avbryt',
    'participants.delete': 'Ta bort',
    
    // AI ANALYSIS
    'ai.title': 'AI-Analys: {boardTitle}',
    'ai.description': 'Analysera {count} anteckningar med AI',
    'ai.notesLabel': 'Anteckningar ({count})',
    'ai.customPrompt': 'Anpassad prompt',
    'ai.defaultPrompt': `Analysera dessa workshop-svar och identifiera de 5-8 viktigaste insikterna.

För varje insight:
- Formulera ett tydligt tema/huvudbudskap
- Ge konkreta exempel från svaren (referera med "Not X")
- Gruppera liknande idéer tillsammans
- Förklara varför detta är viktigt för organisationen

Avsluta med:
- 3-5 konkreta, actionable rekommendationer för nästa steg
- Eventuella mönster, motsättningar eller gap du ser i svaren

Struktur: Använd tydliga rubriker (##) och punktlistor för maximal läsbarhet.`,
    'ai.promptPlaceholder': 'Beskriv vad du vill att AI:n ska fokusera på...',
    'ai.analyzeButton': 'Analysera med AI',
    'ai.aiAnalysisLabel': 'AI-Analys',
    'ai.analyzingStatus': 'Analyserar anteckningar...',
    'ai.analyzingWait': 'Detta kan ta några sekunder',
    'ai.clickToStart': 'Klicka på "Analysera med AI" för att börja',
    'ai.analyze': 'Analysera med AI',
    'ai.analyzing': 'Analyserar...',
    'ai.prompt': 'Sammanfatta huvudteman och insikter från dessa workshop-svar',
    'ai.results': 'AI-Analys',
    'ai.close': 'Stäng',
    'ai.copy': 'Kopiera',
    'ai.error': 'Kunde inte analysera anteckningarna',
    'ai.noNotes': 'Inga anteckningar att analysera',
    'ai.previousAnalyses': 'Tidigare analyser',
    'ai.noPreviousAnalyses': 'Inga tidigare analyser',
    'ai.currentAnalysis': 'Aktuell analys',
    'ai.noAnalysisYet': 'Ingen analys gjord ännu',
    'ai.createdAt': 'Skapad',
    'ai.deleteAnalysis': 'Ta bort analys',
    'ai.noNotesAvailable': 'Inga anteckningar tillgängliga för detta board',
    'ai.customPromptActive': 'Anpassad prompt',
    'ai.resetToDefault': 'Återställ till standard',
    'ai.customized': 'Anpassad',
    'ai.analysisComplete': 'Analys klar!',
    'ai.analysisAvailable': 'AI-analysen är nu tillgänglig',
    'ai.analysisFailed': 'Kunde inte genomföra analysen. Försök igen.',
    'ai.analysisDeleted': 'Analys raderad',
    'ai.analysisDeletedDesc': 'Analysen har tagits bort',
    'ai.deleteFailed': 'Kunde inte radera analysen',
    'ai.copied': 'Kopierat!',
    'ai.copiedDesc': 'Analysen har kopierats till urklipp',
    'ai.copyFailed': 'Kunde inte kopiera. Försök igen.',
    'ai.success': 'Analys klar!',
    
    // BOARDS & NOTES  
    'board.title': 'Board',
    'board.of': 'av',
    'board.notes': 'notes',
    'board.noNotes': 'Inga notes än',
    'board.noNotesYet': 'Inga notes än',
    'board.movedToNext': 'Nästa board',
    'board.syncing': 'Synkar till facilitatorns vy...',
    'board.loading': 'Laddar board...',
    'board.sessionMissing': 'Session saknas',
    'board.sessionMissingDesc': 'Du måste gå med i workshopen igen',
    'board.workshopNotFound': 'Workshop hittades inte',
    'board.workshopNotFoundDesc': 'Kontrollera att workshop-koden är korrekt',
    'board.boardNotFound': 'Board hittades inte',
    'board.boardNotFoundDesc': 'Denna övning kunde inte hittas',
    'board.error': 'Fel',
    'board.loadError': 'Kunde inte ladda workshop-data',
    'board.timeUp': 'Tiden är ute!',
    'board.timeLimitReached': 'Boardens tidsgräns har nåtts',
    'board.noteCreated': 'Note skapad!',
    'board.noteCreatedDesc': 'Din idé har lagts till',
    'board.saveError': 'Kunde inte spara note. Försök igen.',
    'board.deleteOwnOnly': 'Du kan bara ta bort dina egna notes',
    'board.contactFacilitator': 'Kontakta facilitator för att ta bort notes',
    'board.info': 'Info',
    
    // DASHBOARD
    'dashboard.title': 'Mina Workshops',
    'dashboard.createNew': 'Skapa Ny Workshop',
    'dashboard.workshop': 'workshop',
    'dashboard.workshops': 'workshops',
    'dashboard.active': 'Aktiva',
    'dashboard.drafts': 'Utkast',
    'dashboard.archived': 'Arkiverade',
    'dashboard.createdAt': 'Skapad',
    'dashboard.participants': 'deltagare',
    'dashboard.boards': 'boards',
    'dashboard.edit': 'Redigera',
    'dashboard.delete': 'Ta bort',
    'dashboard.open': 'Öppna',
    'dashboard.noWorkshops': 'Inga workshops än',
    'dashboard.comeBack': 'Kom igång genom att skapa din första workshop',
    'dashboard.createWorkshop': 'Skapa Workshop',
    'dashboard.status.active': 'Aktiv',
    'dashboard.status.draft': 'Utkast',
    'dashboard.openWorkshop': 'Öppna Workshop',
    'dashboard.startFacilitating': 'Starta',
    
    // COMMON
    'common.save': 'Spara',
    'common.cancel': 'Avbryt',
    'common.delete': 'Ta bort',
    'common.edit': 'Redigera',
    'common.close': 'Stäng',
    'common.back': 'Tillbaka',
    'common.next': 'Nästa',
    'common.loading': 'Laddar...',
    'common.confirm': 'Bekräfta',
    'common.copied': 'Kopierat!',
    
    // ERRORS & MESSAGES
    'error.workshopNotFound': 'Workshop-koden hittades inte. Kontrollera att koden är korrekt och försök igen.',
    'error.invalidCode': 'Ogiltig kod',
    'error.fillAllFields': 'Fyll i alla fält',
    'error.workshopDraft': 'Denna workshop är inte aktiverad ännu',
    'success.workshopCreated': 'Workshop skapad!',
    'success.workshopUpdated': 'Workshop uppdaterad!',
    'success.noteSaved': 'Anteckning sparad!',
    
    // FOOTER
    'footer.privacy': 'Integritetspolicy',
    'footer.terms': 'Användarvillkor',
    'footer.cookies': 'Cookies',
    'footer.contact': 'Kontakt',
    'footer.rights': 'Alla rättigheter förbehållna.',
    'footer.copyright': '© 2025 Sparkboard. Alla rättigheter förbehållna.',
    
    // NOT FOUND
    'notFound.title': 'Sidan hittades inte',
    'notFound.description': 'Sidan du letar efter finns inte.',
    'notFound.button': 'Tillbaka till startsidan',
    
    // CONTROL PANEL
    'control.importNotes': 'Importera',
    
    // IMPORT NOTES
    'import.title': 'Importera & Klustra Post-its',
    'import.description': 'Importera post-its från andra boards till "{boardTitle}"',
    'import.selectNotes': 'Välj notes',
    'import.defineCategories': 'Kategorier',
    'import.preview': 'Förhandsgranska',
    'import.noNotesAvailable': 'Inga notes tillgängliga från andra boards',
    'import.selectAll': 'Välj alla',
    'import.deselectAll': 'Avmarkera alla',
    'import.selectedCount': '{count} valda',
    'import.noNotesSelected': 'Inga notes valda',
    'import.selectNotesFirst': 'Välj minst en note att importera',
    'import.needCategories': 'Kategorier saknas',
    'import.addAtLeastTwoCategories': 'Lägg till minst två kategorier',
    'import.categoriesLabel': 'Definiera kategorier',
    'import.categoriesDescription': 'AI kommer sortera valda notes in i dessa kategorier',
    'import.categoryPlaceholder': 'Kategori {index}',
    'import.addCategory': 'Lägg till kategori',
    'import.contextLabel': 'Extra kontext (valfritt)',
    'import.contextDescription': 'Ge AI mer information om hur du vill att notes ska sorteras',
    'import.contextPlaceholder': 'T.ex. "Sortera efter genomförbarhet" eller "Fokusera på tekniska lösningar"',
    'import.clustering': 'Klustar...',
    'import.previewClustering': 'Förhandsgranska med AI',
    'import.clusteringComplete': 'Klustring klar!',
    'import.reviewResults': 'Granska resultatet och bekräfta importen',
    'import.clusteringFailed': 'Klustring misslyckades',
    'import.importing': 'Importerar...',
    'import.confirmImport': 'Bekräfta import',
    'import.importSuccess': 'Import klar!',
    'import.notesImported': '{count} notes har importerats',
    'import.importFailed': 'Import misslyckades',
    'import.editCategoriesHint': 'Du kan redigera kategorinamnen genom att klicka på dem',
    'import.categoryNamePlaceholder': 'Kategorinamn',
    'import.method': 'Metod',
    'import.selectMethod': 'Hur vill du importera?',
    'import.manualImport': 'Manuell import',
    'import.manualDescription': 'Importera alla valda notes direkt till "Importerade svar"',
    'import.aiClustering': 'AI-klustring',
    'import.aiDescription': 'Låt AI sortera notes i kategorier automatiskt',
    'import.manualImportComplete': '{count} notes importerades till "Importerade svar"',

    // CREATE WORKSHOP
    'createWorkshop.titleMissing': 'Titel saknas',
    'createWorkshop.titleMissingDesc': 'Ange en titel för din workshop',
    'createWorkshop.noBoards': 'Inga boards',
    'createWorkshop.noBoardsDesc': 'Lägg till minst ett board',
    'createWorkshop.boardTitleMissing': 'Board-titel saknas',
    'createWorkshop.boardTitleMissingDesc': 'Alla boards måste ha en titel',
    'createWorkshop.noQuestions': 'Inga frågor',
    'createWorkshop.noQuestionsDesc': 'Board "{title}" måste ha minst en fråga',
    'createWorkshop.questionMissing': 'Fråga saknas',
    'createWorkshop.questionMissingDesc': 'Alla frågor i "{title}" måste ha text',
    'createWorkshop.draftSaved': 'Utkast sparat',
    'createWorkshop.draftSavedDesc': 'Din workshop har sparats som utkast',
    'createWorkshop.draftSaveFailed': 'Kunde inte spara utkast',
    'createWorkshop.activated': 'Workshop aktiverad!',
    'createWorkshop.activatedDesc': 'Din workshop-kod är: {code}',
    'createWorkshop.saveFailed': 'Kunde inte spara workshop',
    'createWorkshop.saveFailedDesc': 'Försök igen',
    'createWorkshop.loginRequired': 'Du måste vara inloggad',

    // PAYMENT SUCCESS
    'payment.success.title': 'Betalning genomförd!',
    'payment.success.description': 'Tack för att du uppgraderade till Pro',
    'payment.success.features': 'Du har nu tillgång till alla Pro-funktioner!',
    'payment.success.unlimitedWorkshops': 'Obegränsat antal workshops',
    'payment.success.unlimitedParticipants': 'Obegränsat antal deltagare',
    'payment.success.aiAnalysis': 'AI-analys av resultaten',
    'payment.success.updating': 'Uppdaterar ditt konto...',
    'payment.success.retrying': 'Uppdaterar ditt konto (försöker igen)...',
    'payment.success.verifyError': 'Kunde inte verifiera prenumerationen. Försöker igen...',
    'payment.success.goToDashboard': 'Gå till Dashboard',
    'payment.success.welcome': 'Välkommen till Pro!',
    'payment.success.welcomeDesc': 'Du kan nu skapa obegränsat med workshops',

    // PAYMENT CANCELLED
    'payment.cancelled.title': 'Betalning avbruten',
    'payment.cancelled.description': 'Ingen betalning har genomförts',
    'payment.cancelled.info': 'Betalningen avbröts och ditt konto har inte debiterats. Du kan försöka igen när du är redo.',
    'payment.cancelled.tryAgain': 'Försök igen',
    'payment.cancelled.backToDashboard': 'Tillbaka till Dashboard',

    // ACCOUNT SETTINGS
    'account.title': 'Konto & Prenumeration',
    'account.profile': 'Din profil',
    'account.profileInfo': 'Kontoinformation',
    'account.name': 'Namn',
    'account.email': 'E-post',
    'account.subscription': 'Din prenumeration',
    'account.currentPlan': 'Nuvarande plan',
    'account.nextPayment': 'Nästa betalning',
    'account.upgradeCta': 'Uppgradera till Pro för obegränsat workshops, AI-analys och prioriterad support!',
    'account.seePlans': 'Se Pro-planer',
    'account.manageSubscription': 'Hantera din prenumeration',
    'account.manageInfo': 'Du kan när som helst:',
    'account.cancelInfo': 'Avbryta din prenumeration (du behåller Pro till periodens slut)',
    'account.changePayment': 'Ändra från månadsvis till årlig betalning (eller tvärtom)',
    'account.updateMethod': 'Uppdatera betalningsmetod',
    'account.viewInvoices': 'Se alla dina fakturor',
    'account.cancellationWarning': 'Vid avbokning: Du behåller Pro-funktioner till {date}, därefter nedgraderas du automatiskt till Free (max 1 workshop).',
    'account.manageInStripe': 'Hantera prenumeration i Stripe',
    'account.opening': 'Öppnar...',
    'account.refreshStatus': 'Uppdatera prenumerationsstatus',
    'account.statusUpdated': 'Status uppdaterad',
    'account.statusSynced': 'Din prenumerationsstatus är nu synkroniserad.',
    'account.updateFailed': 'Kunde inte uppdatera',
    'account.tryAgainLater': 'Försök igen om en stund.',
    'account.errorOccurred': 'Ett fel uppstod',
    'account.stripeError': 'Kunde inte öppna Stripe-portalen. Försök igen.',
    'account.enterpriseTitle': 'Curago Enterprise',
    'account.enterpriseInfo': 'Din prenumeration hanteras av din organisation. Kontakta din administratör för ändringar.',
    'account.featuresTitle': 'Funktioner i din plan',
    'account.activeWorkshops': '{count} aktiva workshops',
    'account.unlimitedWorkshops': 'Obegränsat aktiva workshops',
    'account.unlimitedParticipants': 'Obegränsat deltagare',
    'account.maxParticipants': 'Max {count} deltagare per workshop',
    'account.aiAnalysis': 'AI-analys av resultat',
    'account.prioritySupport': 'Prioriterad support',
    'account.proOnly': '(endast Pro)',

    // UPGRADE PAGE
    'upgrade.title': 'Välj din plan',
    'upgrade.subtitle': 'Skapa workshops som passar dina behov',
    'upgrade.free.title': 'Sparkboard Free',
    'upgrade.free.price': '0 SEK',
    'upgrade.free.period': '/alltid',
    'upgrade.free.workshop': '1 aktiv workshop',
    'upgrade.free.participants': 'Max 5 deltagare per workshop',
    'upgrade.free.noAi': 'AI-analys',
    'upgrade.free.noSupport': 'Prioriterad support',
    'upgrade.free.currentPlan': 'Din nuvarande plan',
    'upgrade.monthly.title': 'Sparkboard Pro Monthly',
    'upgrade.monthly.price': '99 SEK',
    'upgrade.monthly.period': '/månad',
    'upgrade.yearly.title': 'Sparkboard Pro Yearly',
    'upgrade.yearly.price': '950 SEK',
    'upgrade.yearly.period': '/år',
    'upgrade.yearly.save': 'Spara 238 SEK',
    'upgrade.yearly.saveMonths': 'Spara nästan 2 månader!',
    'upgrade.pro.workshops': 'Obegränsat workshops',
    'upgrade.pro.participants': 'Obegränsat deltagare',
    'upgrade.pro.ai': 'AI-analys',
    'upgrade.pro.support': 'Prioriterad support',
    'upgrade.button': 'Uppgradera nu',
    'upgrade.loading': 'Laddar...',
    'upgrade.error': 'Något gick fel. Försök igen.',

    // DASHBOARD TOASTS
    'dashboard.workshopDeleted': 'Workshop raderad',
    'dashboard.workshopDeletedDesc': 'Workshopen har tagits bort',
    'dashboard.deleteFailed': 'Kunde inte radera workshop',
    'dashboard.loadFailed': 'Kunde inte ladda workshops',
    'dashboard.workshopDuplicated': 'Workshop duplicerad!',
    'dashboard.workshopDuplicatedDesc': 'En kopia av workshopen har skapats',
    'dashboard.duplicateFailed': 'Kunde inte duplicera workshop',
    'dashboard.duplicate': 'Duplicera',
    'dashboard.showQR': 'Visa QR',
    'dashboard.freePlanWarning': 'Du har nått gränsen på 1 workshop.',
    'dashboard.upgradeForMore': 'Uppgradera till Pro',
    'dashboard.forUnlimited': 'för obegränsat antal workshops!',
    'dashboard.workshopsMigrated': 'Dina workshops är nu kopplade till ditt konto!',
    'dashboard.workshopsMigratedDesc': '{count} workshop(s) har automatiskt kopplats till din nya inloggning.',
    'dashboard.checking': 'Kontrollerar dina workshops...',
    'dashboard.pleaseWait': 'Vänligen vänta',
    'dashboard.takesSeconds': 'Detta tar bara några sekunder',
    'dashboard.migrationError': 'Migration Error',
    'dashboard.tryAgain': 'Försök igen',

    // AI PRO BLOCKING
    'ai.proOnly': '(endast Pro)',
    'ai.proRequired': 'AI-analys kräver Pro',
    'ai.proRequiredDesc': 'Uppgradera till Pro för att låsa upp AI-driven analys av dina workshop-resultat.',
    'ai.benefit1': 'AI-driven insiktsanalys',
    'ai.benefit2': 'Obegränsat med workshops',
    'ai.benefit3': 'Obegränsat antal deltagare',
    'ai.upgradeNow': 'Uppgradera till Pro',
    'ai.requiresProToast': 'AI-analys kräver Pro-prenumeration',

    // QR DIALOG
    'qr.title': 'Workshop QR-kod',
    'qr.description': 'Dela denna kod eller QR-kod med dina deltagare',
    'qr.download': 'Ladda ner QR-kod',
    'qr.code': 'Workshop-kod',
    'qr.participantLink': 'Deltagarlänk',
    'qr.copy': 'Kopiera',
    'qr.copied': 'Kopierad!',
    'qr.copiedDesc': 'Länken har kopierats',

    // UPGRADE PAGE DESCRIPTIONS
    'upgrade.free.description': 'Perfekt för att testa Sparkboard och köra enstaka workshops',
    'upgrade.free.basicFeatures': 'Grundläggande funktioner',
    'upgrade.monthly.description': 'Full tillgång till alla funktioner - flexibelt månadsabonnemang',
    'upgrade.yearly.description': 'Bästa priset - full tillgång hela året för professionella facilitatorer',
    'upgrade.pro.export': 'Export till Excel och PDF',

    // CREATE WORKSHOP PAGE UI
    'createWorkshop.backToDashboard': 'Tillbaka till Dashboard',
    'createWorkshop.badge': 'Ny Workshop',
    'createWorkshop.pageTitle': 'Skapa Workshop',
    'createWorkshop.pageSubtitle': 'Bygg din interaktiva workshop med boards och frågor',
    'createWorkshop.basicInfo': 'Grundinformation',
    'createWorkshop.basicInfoDesc': 'Beskriv din workshop',
    'createWorkshop.workshopTitleLabel': 'Workshop Titel *',
    'createWorkshop.workshopTitlePlaceholder': 'T.ex. Strategi Workshop 2024',
    'createWorkshop.descriptionLabel': 'Beskrivning',
    'createWorkshop.descriptionPlaceholder': 'Beskriv syftet med workshopen...',
    'createWorkshop.boardsSection': 'Boards & Övningar',
    'createWorkshop.boardsSectionDesc': 'Lägg till olika övningar och frågor',
    'createWorkshop.addBoardButton': 'Lägg till Board',
    'createWorkshop.noBoardsYet': 'Inga boards än',
    'createWorkshop.noBoardsStartHint': 'Börja med att lägga till ditt första board',
    'createWorkshop.cannotEditWithResponses': 'Du kan inte redigera en redan publicerad workshop som innehåller deltagarnas svar',
    'createWorkshop.saveDraftButton': 'Spara som Utkast',
    'createWorkshop.activateButton': 'Aktivera Workshop',
    'createWorkshop.tipsTitle': '💡 Tips för bra workshops',
    'createWorkshop.tip1': 'Använd tydliga och specifika frågor',
    'createWorkshop.tip2': 'Sätt realistiska tidsgränser för varje board',
    'createWorkshop.tip3': 'Variera frågorna mellan reflektiva och kreativa',
    'createWorkshop.tip4': 'Färgkodning hjälper deltagare hålla koll på olika övningar',
    'createWorkshop.workshopCountInfo': '{count} av {limit} workshop använd',
    'createWorkshop.qrDownloaded': 'QR-kod nedladdad!',
    'createWorkshop.qrDownloadedDesc': 'QR-koden har sparats som en bild',

    // FACILITATOR CONTROL TOASTS
    'facilitator.workshopMissing': 'Workshop saknas',
    'facilitator.workshopMissingDesc': 'Kunde inte hitta workshopen. Återgår till dashboard.',
    'facilitator.loadError': 'Fel',
    'facilitator.loadErrorDesc': 'Kunde inte ladda workshop-data',
    'facilitator.timeUp': 'Tiden är ute!',
    'facilitator.timeUpDesc': 'Boardens tidsgräns har nåtts',
    'facilitator.twoMinutesLeft': '2 minuter kvar!',
    'facilitator.twoMinutesLeftDesc': 'Boardens tid håller på att ta slut',
    'facilitator.nextBoardToast': 'Nästa board!',
    'facilitator.nextBoardDesc': 'Nu på: {title}',
    'facilitator.switchError': 'Fel',
    'facilitator.switchErrorDesc': 'Kunde inte byta board',
    'facilitator.pdfGenerated': 'PDF genererad!',
    'facilitator.pdfGeneratedDesc': 'Din workshop-rapport har laddats ner',
    'facilitator.pdfError': 'Fel vid PDF-generering',
    'facilitator.pdfErrorDesc': 'Kunde inte skapa PDF. Försök igen.',
    'facilitator.noteDeleted': 'Note borttagen',
    'facilitator.noteDeletedDesc': 'Sticky note har tagits bort',
    'facilitator.deleteError': 'Fel',
    'facilitator.deleteErrorDesc': 'Kunde inte ta bort note',
    'facilitator.noteMoved': 'Note flyttad',
    'facilitator.noteMovedDesc': 'Sticky note har flyttats till ny kategori',
    'facilitator.moveError': 'Fel',
    'facilitator.moveErrorDesc': 'Kunde inte flytta note',
    'facilitator.participantDeleted': 'Deltagare borttagen',
    'facilitator.participantDeletedDesc': 'Deltagaren och deras anteckningar har tagits bort från workshopen',
    'facilitator.participantDeleteError': 'Fel',
    'facilitator.participantDeleteErrorDesc': 'Kunde inte ta bort deltagare',
    'facilitator.participantNotesDeleteError': 'Kunde inte ta bort deltagarens anteckningar',
    'facilitator.timerUpdateError': 'Kunde inte uppdatera timer',
    'facilitator.showQR': 'Visa QR',
    'facilitator.couldNotSwitchBoard': 'Kunde inte byta board för deltagare',

    // UPGRADE REQUIRED DIALOG
    'upgradeRequired.title': 'Uppgradera till Pro',
    'upgradeRequired.limitReached': 'Du har nått gränsen för gratis-planen (1 aktiv workshop).',
    'upgradeRequired.unlockFeatures': 'Uppgradera till Pro för att skapa obegränsat med workshops:',
    'upgradeRequired.unlimitedWorkshops': 'Obegränsat workshops',
    'upgradeRequired.unlimitedParticipants': 'Obegränsat deltagare',
    'upgradeRequired.aiAnalysis': 'AI-analys av resultat',
    'upgradeRequired.prioritySupport': 'Prioriterad support',
    'upgradeRequired.price': 'Från endast 99 SEK/månad',
    'upgradeRequired.cancel': 'Avbryt',
    'upgradeRequired.seePlans': 'Se planer',

    // IMPORT NOTES MOBILE TABS
    'import.selectMobile': 'Välj',
    'import.methodMobile': 'Metod',
    'import.aiMobile': 'AI',
    'import.previewMobile': 'Granska',
    'import.existingCategories': 'Befintliga kategorier',
    'import.newCategories': 'Nya kategorier',
    'import.existingBadge': 'Befintlig',
    'import.addsToBadge': 'Läggs till',
    'import.newBadge': 'Ny',

    // PDF EXPORT
    'pdf.date': 'Datum',
    'pdf.participants': 'Deltagare',
    'pdf.board': 'Board',
    'pdf.timeLimit': 'Tidsgräns',
    'pdf.minutes': 'minuter',
    'pdf.question': 'Fråga',
    'pdf.noAnswers': 'Inga svar',
    'pdf.aiAnalysis': '🤖 AI-Analys',
  },
  
  en: {
    // LANDING
    'app.title': 'Sparkboard',
    'app.description': 'Sparkboard is an interactive platform for creative workshops with sticky-notes and AI analysis',
    'app.tagline': 'Collaborate, brainstorm and create together',
    'landing.facilitator.title': 'Facilitator',
    'landing.facilitator.description': 'Create and manage workshops. Invite participants and get real-time insights.',
    'landing.facilitator.button': 'Create Workshop',
    'landing.participant.title': 'Participant',
    'landing.participant.description': 'Join a workshop with your unique code and share your ideas.',
    'landing.participant.button': 'Join Workshop',
    
    // FEATURES
    'landing.features.realtime.title': 'Collaborate in real-time',
    'landing.features.realtime.description': 'See all contributions instantly as they are created',
    'landing.features.easy.title': 'Easy access',
    'landing.features.easy.description': 'Join via 6-digit code or QR - no account needed',
    'landing.features.responsive.title': 'Responsive design',
    'landing.features.responsive.description': 'Works perfectly on mobile and desktop',
    'landing.features.ai.title': 'AI Analysis',
    'landing.features.ai.description': 'Summarizes ideas, finds themes and gives recommendations automatically',
    
    // AUTH & NAVIGATION
    'auth.login': 'Log in',
    'auth.signup': 'Sign up',
    'auth.logout': 'Log out',
    'auth.myaccount': 'My account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.company': 'Company name',
    'auth.facilitatorPin': 'Facilitator PIN',
    'auth.createPin': 'Create PIN',
    'auth.enterPin': 'Enter your PIN code',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPin': 'Forgot PIN?',
    'auth.register': 'Register',
    'auth.backToLogin': 'Back to login',
    'auth.resetPin': 'Reset PIN',
    'auth.resetSuccess': 'PIN reset! You can now log in with your new PIN.',
    'auth.resetError': 'Company not found',
    'auth.loginSuccess': 'Welcome back!',
    'auth.loginError': 'Incorrect PIN code',
    'auth.registerSuccess': 'Account created! You are now logged in.',
    'auth.registerError': 'Company name already in use',
    'auth.loginTitle': 'Log in',
    'auth.loginDescription': 'Log in to your account to manage workshops',
    'auth.name': 'Name',
    'auth.pin': 'PIN code',
    'auth.loginButton': 'Log in',
    'auth.createAccount': 'Create account',
    'auth.or': 'or',
    'auth.registerTitle': 'Create account',
    'auth.registerDescription': 'Create a new facilitator account',
    'auth.nameOptional': 'Name (optional)',
    'auth.nameOptionalPlaceholder': 'Your name',
    'auth.confirmPin': 'Confirm PIN',
    'auth.securityInfo': 'Add a security question to recover your PIN (optional)',
    'auth.securityQuestion': 'Security question',
    'auth.securityQuestionPlaceholder': 'E.g. What is your first pet\'s name?',
    'auth.securityAnswer': 'Answer',
    'auth.securityAnswerPlaceholder': 'Your answer',
    'auth.cancel': 'Cancel',
    'auth.createAccountButton': 'Create account',
    'auth.pinMismatch': 'PINs do not match',
    'auth.pinMismatchDesc': 'Please make sure you entered the same PIN twice',
    'auth.welcome': 'Welcome!',
    'auth.welcomeDesc': 'Your account has been created',
    'auth.registerFailed': 'Could not create account',
    'auth.accountLocked': 'Account locked',
    'auth.accountLockedDesc': 'Too many failed login attempts. Please try again later.',
    'auth.nameRequired': 'Name required',
    'auth.nameRequiredDesc': 'Enter your name to log in',
    'auth.accountNotFound': 'Account not found',
    'auth.accountNotFoundDesc': 'There is no account with that name',
    'auth.loggedIn': 'Logged in',
    'auth.welcomeBack': 'Welcome back!',
    'auth.incorrectPin': 'Incorrect PIN code',
    'auth.attemptsLeft': '{count} attempts left',
    'auth.accountNowLocked': 'Account is now locked due to too many failed attempts',
    'auth.noAccountSelected': 'No account selected',
    'auth.pinReset': 'PIN reset',
    'auth.pinResetDesc': 'You can now log in with your new PIN',
    'auth.resetFailed': 'Reset failed',
    'auth.resetPinTitle': 'Reset PIN',
    'auth.resetPinDescription': 'Answer your security question to reset your PIN',
    'auth.securityQuestionLabel': 'Your security question',
    'auth.yourAnswer': 'Your answer',
    'auth.yourAnswerPlaceholder': 'Enter your answer',
    'auth.newPin': 'New PIN',
    'auth.confirmNewPin': 'Confirm new PIN',
    'auth.resetButton': 'Reset PIN',
    'auth.pinPlaceholder': '••••••',
    'auth.namePlaceholder': 'Your name',
    'auth.lockedOut': 'Account locked due to too many failed login attempts. Please wait 15 minutes.',
    'auth.attemptsRemaining': '{count} login attempts remaining',
    
    // CREATE WORKSHOP
    'workshop.create': 'Create Workshop',
    'workshop.new': 'New Workshop',
    'workshop.title': 'Title',
    'workshop.titlePlaceholder': 'My Workshop',
    'workshop.description': 'Description',
    'workshop.descriptionPlaceholder': 'Describe your workshop...',
    'workshop.addBoard': 'Add Board',
    'workshop.boardTitle': 'Board title',
    'workshop.addQuestion': 'Add Question',
    'workshop.questionText': 'Question text',
    'workshop.timeLimit': 'Time limit (minutes)',
    'workshop.saveDraft': 'Save as draft',
    'workshop.activate': 'Activate Workshop',
    'workshop.update': 'Update Workshop',
    'workshop.code': 'Workshop code',
    'workshop.shareCode': 'Share this code with participants',
    'workshop.copyCode': 'Copy code',
    'workshop.downloadQR': 'Download QR code',
    'workshop.boards': 'Boards',
    'workshop.maxBoards': 'Max 10 boards',
    'workshop.dragToReorder': 'Drag to reorder',
    'workshop.fillTitle': 'Fill in a title',
    'workshop.addAtLeastOneBoard': 'Add at least one board',
    'workshop.allBoardsNeedTitles': 'All boards need titles',
    'workshop.allBoardsNeedQuestions': 'All boards need at least one question',
    
    // BOARD
    'boardCard.label': 'Board {index}',
    'boardCard.title': 'Title',
    'boardCard.titlePlaceholder': 'My Question',
    'boardCard.timeLimit': 'Time limit (minutes)',
    'boardCard.questions': 'Questions ({current}/{max})',
    'boardCard.questionPlaceholder': 'Question {index}',
    'boardCard.addQuestion': 'Add question',
    
    // JOIN WORKSHOP
    'join.title': 'Join Workshop',
    'join.welcome': 'Welcome',
    'join.enterCode': 'Enter your 6-digit workshop code and your name',
    'join.code': 'Workshop code',
    'join.codePlaceholder': '123456',
    'join.name': 'Your name',
    'join.namePlaceholder': 'John Doe',
    'join.button': 'Join Workshop',
    'join.scanQR': 'Scan QR code',
    'join.cancel': 'Cancel',
    'join.getCodeFrom': 'Get the workshop code from your facilitator',
    'join.joining': 'Joining...',
    'join.invalidCode': 'Invalid workshop code',
    'join.enterName': 'Enter your name',
    'join.badge': 'Join',
    'join.connectTitle': 'Connect to Workshop',
    'join.characters': '{count}/6 characters',
    'join.infoTitle': 'Information',
    'join.infoCode': 'The code consists of 6 letters and numbers',
    'join.infoNoAccount': 'You don\'t need to create an account to participate',
    'join.infoNameVisible': 'Your name will be visible to other participants',
    'join.qrScanned': 'QR code scanned!',
    'join.qrCode': 'Workshop code: {code}',
    'join.cameraError': 'Cannot start camera',
    'join.cameraPermission': 'Check that your browser has camera access',
    'join.welcomeToast': 'Welcome!',
    'join.connectedTo': 'You have joined "{name}"',
    'join.connectionFailed': 'Could not connect',
    'join.invalidCodeLength': 'Workshop code must be 6 characters long',
    'join.nameMissing': 'Name missing',
    'join.nameMinLength': 'Please enter a name (at least 2 characters)',
    'join.notFound': 'Workshop code not found. Check that the code is correct.',
    'join.notActive': 'This workshop is not active right now.',
    'join.limitReached': 'The workshop has reached the maximum number of participants.',
    'join.genericError': 'Something went wrong. Please try again.',
    'join.scanQRTitle': 'Scan QR code',
    'join.scanQRDescription': 'Point your camera at the QR code to automatically fill in the workshop code',
    'join.scanQRHint': 'Make sure the QR code is within the green frame',
    
    // WORKSHOP SESSION (PARTICIPANT)
    'session.workshop': 'Workshop',
    'session.timeRemaining': 'Time remaining',
    'session.addNote': 'Add note',
    'session.yourNote': 'Your note',
    'session.submit': 'Submit',
    'session.notes': 'notes',
    'session.noNotes': 'No notes yet',
    'session.waiting': 'Waiting for next board...',
    'session.currentBoard': 'Current board',
    
    // ADD NOTE
    'addNote.title': 'Add note',
    'addNote.description': 'Select a question and write your note',
    'addNote.selectQuestion': 'Select question',
    'addNote.selectPlaceholder': 'Select a question...',
    'addNote.noteContent': 'Note',
    'addNote.notePlaceholder': 'Write your note here...',
    'addNote.submit': 'Add',
    'addNote.cancel': 'Cancel',
    
    // NAVIGATION
    'nav.back': 'Back',
    'nav.login': 'Log in',
    'nav.logout': 'Log out',
    'nav.myWorkshops': 'My Workshops',
    'nav.account': 'Account',
    'nav.upgrade': 'Upgrade',
    
    // FACILITATOR CONTROL
    'facilitator.control': 'Facilitator Control',
    'facilitator.workshop': 'Workshop',
    'control.title': 'Facilitator Control',
    'control.workshop': 'Workshop',
    'control.start': 'Start',
    'control.pause': 'Pause',
    'control.resume': 'Resume',
    'control.nextBoard': 'Next Board',
    'control.prevBoard': 'Previous Board',
    'control.aiAnalysis': 'AI Analysis',
    'control.exportPDF': 'Export PDF',
    'control.soundOn': 'Sound On',
    'control.soundOff': 'Sound Off',
    'control.hideControls': 'Hide controls',
    'control.showControls': 'Show controls',
    'control.hideParticipants': 'Hide participants',
    'control.showParticipants': 'Show participants',
    'facilitator.startTimer': 'Start',
    'facilitator.pauseTimer': 'Pause',
    'facilitator.nextBoard': 'Next Board',
    'facilitator.previousBoard': 'Previous Board',
    'facilitator.aiAnalysis': 'AI Analysis',
    'facilitator.exportPDF': 'Export PDF',
    'facilitator.soundOn': 'Sound On',
    'facilitator.soundOff': 'Sound Off',
    'facilitator.participants': 'Participants',
    'facilitator.hideParticipants': 'Hide participants',
    'facilitator.showParticipants': 'Show participants',
    'facilitator.noParticipants': 'No participants yet',
    'facilitator.board': 'Board',
    'facilitator.of': 'of',
    'facilitator.paused': 'Paused',
    'facilitator.running': 'Running',
    
    // PARTICIPANTS
    'participants.title': 'Participants ({count})',
    'participants.noParticipantsYet': 'No participants yet',
    'participants.noParticipants': 'No participants yet',
    'participants.deleteConfirm': 'Remove participant?',
    'participants.deleteConfirmDesc': 'Are you sure you want to remove {name}? All their notes will be deleted.',
    'participants.cancel': 'Cancel',
    'participants.delete': 'Delete',
    
    // AI ANALYSIS
    'ai.title': 'AI Analysis: {boardTitle}',
    'ai.description': 'Analyze {count} notes with AI',
    'ai.notesLabel': 'Notes ({count})',
    'ai.customPrompt': 'Custom prompt',
    'ai.defaultPrompt': `Analyze these workshop responses and identify the 5-8 most important insights.

For each insight:
- Formulate a clear theme/key message
- Provide concrete examples from responses (reference as "Note X")
- Group similar ideas together
- Explain why this matters for the organization

Conclude with:
- 3-5 concrete, actionable recommendations for next steps
- Any patterns, contradictions, or gaps you see in the responses

Structure: Use clear headings (##) and bullet points for maximum readability.`,
    'ai.promptPlaceholder': 'Describe what you want the AI to focus on...',
    'ai.analyzeButton': 'Analyze with AI',
    'ai.aiAnalysisLabel': 'AI Analysis',
    'ai.analyzingStatus': 'Analyzing notes...',
    'ai.analyzingWait': 'This may take a few seconds',
    'ai.clickToStart': 'Click "Analyze with AI" to start',
    'ai.analyze': 'Analyze with AI',
    'ai.analyzing': 'Analyzing...',
    'ai.prompt': 'Summarize main themes and insights from these workshop responses',
    'ai.results': 'AI Analysis',
    'ai.close': 'Close',
    'ai.copy': 'Copy',
    'ai.error': 'Could not analyze notes',
    'ai.noNotes': 'No notes to analyze',
    'ai.success': 'Analysis complete!',
    'ai.previousAnalyses': 'Previous analyses',
    'ai.noPreviousAnalyses': 'No previous analyses',
    'ai.currentAnalysis': 'Current analysis',
    'ai.noAnalysisYet': 'No analysis done yet',
    'ai.createdAt': 'Created',
    'ai.deleteAnalysis': 'Delete analysis',
    'ai.noNotesAvailable': 'No notes available for this board',
    'ai.customPromptActive': 'Custom prompt',
    'ai.resetToDefault': 'Reset to default',
    'ai.customized': 'Customized',
    'ai.analysisComplete': 'Analysis complete!',
    'ai.analysisAvailable': 'AI analysis is now available',
    'ai.analysisFailed': 'Could not complete the analysis. Please try again.',
    'ai.analysisDeleted': 'Analysis deleted',
    'ai.analysisDeletedDesc': 'The analysis has been removed',
    'ai.deleteFailed': 'Could not delete the analysis',
    'ai.copied': 'Copied!',
    'ai.copiedDesc': 'The analysis has been copied to clipboard',
    'ai.copyFailed': 'Could not copy. Please try again.',
    
    // BOARDS & NOTES
    'board.title': 'Board',
    'board.of': 'of',
    'board.notes': 'notes',
    'board.noNotes': 'No notes yet',
    'board.noNotesYet': 'No notes yet',
    'board.movedToNext': 'Next board',
    'board.syncing': 'Syncing to facilitator view...',
    'board.loading': 'Loading board...',
    'board.sessionMissing': 'Session missing',
    'board.sessionMissingDesc': 'You need to rejoin the workshop',
    'board.workshopNotFound': 'Workshop not found',
    'board.workshopNotFoundDesc': 'Check that the workshop code is correct',
    'board.boardNotFound': 'Board not found',
    'board.boardNotFoundDesc': 'This exercise could not be found',
    'board.error': 'Error',
    'board.loadError': 'Could not load workshop data',
    'board.timeUp': 'Time is up!',
    'board.timeLimitReached': 'The board time limit has been reached',
    'board.noteCreated': 'Note created!',
    'board.noteCreatedDesc': 'Your idea has been added',
    'board.saveError': 'Could not save note. Please try again.',
    'board.deleteOwnOnly': 'You can only delete your own notes',
    'board.contactFacilitator': 'Contact the facilitator to delete notes',
    'board.info': 'Info',
    
    // DASHBOARD
    'dashboard.title': 'My Workshops',
    'dashboard.createNew': 'Create New Workshop',
    'dashboard.workshop': 'workshop',
    'dashboard.workshops': 'workshops',
    'dashboard.active': 'Active',
    'dashboard.drafts': 'Drafts',
    'dashboard.archived': 'Archived',
    'dashboard.createdAt': 'Created',
    'dashboard.participants': 'participants',
    'dashboard.boards': 'boards',
    'dashboard.edit': 'Edit',
    'dashboard.delete': 'Delete',
    'dashboard.open': 'Open',
    'dashboard.noWorkshops': 'No workshops yet',
    'dashboard.comeBack': 'Get started by creating your first workshop',
    'dashboard.createWorkshop': 'Create Workshop',
    'dashboard.status.active': 'Active',
    'dashboard.status.draft': 'Draft',
    'dashboard.openWorkshop': 'Open Workshop',
    'dashboard.startFacilitating': 'Start',
    
    // COMMON
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.loading': 'Loading...',
    'common.confirm': 'Confirm',
    'common.copied': 'Copied!',
    
    // ERRORS & MESSAGES
    'error.workshopNotFound': 'Workshop code not found. Check that the code is correct and try again.',
    'error.invalidCode': 'Invalid code',
    'error.fillAllFields': 'Fill in all fields',
    'error.workshopDraft': 'This workshop is not activated yet',
    'success.workshopCreated': 'Workshop created!',
    'success.workshopUpdated': 'Workshop updated!',
    'success.noteSaved': 'Note saved!',
    
    // FOOTER
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookies',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.copyright': '© 2025 Sparkboard. All rights reserved.',
    
    // NOT FOUND
    'notFound.title': 'Page not found',
    'notFound.description': 'The page you are looking for does not exist.',
    'notFound.button': 'Back to home',
    
    // CONTROL PANEL
    'control.importNotes': 'Import',
    
    // IMPORT NOTES
    'import.title': 'Import & Cluster Post-its',
    'import.description': 'Import post-its from other boards to "{boardTitle}"',
    'import.selectNotes': 'Select notes',
    'import.defineCategories': 'Categories',
    'import.preview': 'Preview',
    'import.noNotesAvailable': 'No notes available from other boards',
    'import.selectAll': 'Select all',
    'import.deselectAll': 'Deselect all',
    'import.selectedCount': '{count} selected',
    'import.noNotesSelected': 'No notes selected',
    'import.selectNotesFirst': 'Select at least one note to import',
    'import.needCategories': 'Categories missing',
    'import.addAtLeastTwoCategories': 'Add at least two categories',
    'import.categoriesLabel': 'Define categories',
    'import.categoriesDescription': 'AI will sort selected notes into these categories',
    'import.categoryPlaceholder': 'Category {index}',
    'import.addCategory': 'Add category',
    'import.contextLabel': 'Extra context (optional)',
    'import.contextDescription': 'Give AI more information about how you want notes sorted',
    'import.contextPlaceholder': 'E.g. "Sort by feasibility" or "Focus on technical solutions"',
    'import.clustering': 'Clustering...',
    'import.previewClustering': 'Preview with AI',
    'import.clusteringComplete': 'Clustering complete!',
    'import.reviewResults': 'Review the result and confirm import',
    'import.clusteringFailed': 'Clustering failed',
    'import.importing': 'Importing...',
    'import.confirmImport': 'Confirm import',
    'import.importSuccess': 'Import complete!',
    'import.notesImported': '{count} notes have been imported',
    'import.importFailed': 'Import failed',
    'import.editCategoriesHint': 'You can edit category names by clicking on them',
    'import.categoryNamePlaceholder': 'Category name',
    'import.method': 'Method',
    'import.selectMethod': 'How do you want to import?',
    'import.manualImport': 'Manual import',
    'import.manualDescription': 'Import all selected notes directly to "Imported answers"',
    'import.aiClustering': 'AI clustering',
    'import.aiDescription': 'Let AI sort notes into categories automatically',
    'import.manualImportComplete': '{count} notes were imported to "Imported answers"',

    // CREATE WORKSHOP
    'createWorkshop.titleMissing': 'Title missing',
    'createWorkshop.titleMissingDesc': 'Enter a title for your workshop',
    'createWorkshop.noBoards': 'No boards',
    'createWorkshop.noBoardsDesc': 'Add at least one board',
    'createWorkshop.boardTitleMissing': 'Board title missing',
    'createWorkshop.boardTitleMissingDesc': 'All boards must have a title',
    'createWorkshop.noQuestions': 'No questions',
    'createWorkshop.noQuestionsDesc': 'Board "{title}" must have at least one question',
    'createWorkshop.questionMissing': 'Question missing',
    'createWorkshop.questionMissingDesc': 'All questions in "{title}" must have text',
    'createWorkshop.draftSaved': 'Draft saved',
    'createWorkshop.draftSavedDesc': 'Your workshop has been saved as a draft',
    'createWorkshop.draftSaveFailed': 'Could not save draft',
    'createWorkshop.activated': 'Workshop activated!',
    'createWorkshop.activatedDesc': 'Your workshop code is: {code}',
    'createWorkshop.saveFailed': 'Could not save workshop',
    'createWorkshop.saveFailedDesc': 'Please try again',
    'createWorkshop.loginRequired': 'You must be logged in',

    // PAYMENT SUCCESS
    'payment.success.title': 'Payment completed!',
    'payment.success.description': 'Thank you for upgrading to Pro',
    'payment.success.features': 'You now have access to all Pro features!',
    'payment.success.unlimitedWorkshops': 'Unlimited workshops',
    'payment.success.unlimitedParticipants': 'Unlimited participants',
    'payment.success.aiAnalysis': 'AI analysis of results',
    'payment.success.updating': 'Updating your account...',
    'payment.success.retrying': 'Updating your account (retrying)...',
    'payment.success.verifyError': 'Could not verify subscription. Retrying...',
    'payment.success.goToDashboard': 'Go to Dashboard',
    'payment.success.welcome': 'Welcome to Pro!',
    'payment.success.welcomeDesc': 'You can now create unlimited workshops',

    // PAYMENT CANCELLED
    'payment.cancelled.title': 'Payment cancelled',
    'payment.cancelled.description': 'No payment was processed',
    'payment.cancelled.info': 'The payment was cancelled and your account was not charged. You can try again when ready.',
    'payment.cancelled.tryAgain': 'Try again',
    'payment.cancelled.backToDashboard': 'Back to Dashboard',

    // ACCOUNT SETTINGS
    'account.title': 'Account & Subscription',
    'account.profile': 'Your profile',
    'account.profileInfo': 'Account information',
    'account.name': 'Name',
    'account.email': 'Email',
    'account.subscription': 'Your subscription',
    'account.currentPlan': 'Current plan',
    'account.nextPayment': 'Next payment',
    'account.upgradeCta': 'Upgrade to Pro for unlimited workshops, AI analysis and priority support!',
    'account.seePlans': 'See Pro plans',
    'account.manageSubscription': 'Manage your subscription',
    'account.manageInfo': 'You can at any time:',
    'account.cancelInfo': 'Cancel your subscription (you keep Pro until end of period)',
    'account.changePayment': 'Switch from monthly to yearly payment (or vice versa)',
    'account.updateMethod': 'Update payment method',
    'account.viewInvoices': 'View all your invoices',
    'account.cancellationWarning': 'Upon cancellation: You keep Pro features until {date}, then automatically downgraded to Free (max 1 workshop).',
    'account.manageInStripe': 'Manage subscription in Stripe',
    'account.opening': 'Opening...',
    'account.refreshStatus': 'Refresh subscription status',
    'account.statusUpdated': 'Status updated',
    'account.statusSynced': 'Your subscription status is now synced.',
    'account.updateFailed': 'Could not update',
    'account.tryAgainLater': 'Try again later.',
    'account.errorOccurred': 'An error occurred',
    'account.stripeError': 'Could not open Stripe portal. Try again.',
    'account.enterpriseTitle': 'Curago Enterprise',
    'account.enterpriseInfo': 'Your subscription is managed by your organization. Contact your admin for changes.',
    'account.featuresTitle': 'Features in your plan',
    'account.activeWorkshops': '{count} active workshops',
    'account.unlimitedWorkshops': 'Unlimited active workshops',
    'account.unlimitedParticipants': 'Unlimited participants',
    'account.maxParticipants': 'Max {count} participants per workshop',
    'account.aiAnalysis': 'AI analysis of results',
    'account.prioritySupport': 'Priority support',
    'account.proOnly': '(Pro only)',

    // UPGRADE PAGE
    'upgrade.title': 'Choose your plan',
    'upgrade.subtitle': 'Create workshops that fit your needs',
    'upgrade.free.title': 'Sparkboard Free',
    'upgrade.free.price': '0 SEK',
    'upgrade.free.period': '/forever',
    'upgrade.free.workshop': '1 active workshop',
    'upgrade.free.participants': 'Max 5 participants per workshop',
    'upgrade.free.noAi': 'AI analysis',
    'upgrade.free.noSupport': 'Priority support',
    'upgrade.free.currentPlan': 'Your current plan',
    'upgrade.monthly.title': 'Sparkboard Pro Monthly',
    'upgrade.monthly.price': '99 SEK',
    'upgrade.monthly.period': '/month',
    'upgrade.yearly.title': 'Sparkboard Pro Yearly',
    'upgrade.yearly.price': '950 SEK',
    'upgrade.yearly.period': '/year',
    'upgrade.yearly.save': 'Save 238 SEK',
    'upgrade.yearly.saveMonths': 'Save almost 2 months!',
    'upgrade.pro.workshops': 'Unlimited workshops',
    'upgrade.pro.participants': 'Unlimited participants',
    'upgrade.pro.ai': 'AI analysis',
    'upgrade.pro.support': 'Priority support',
    'upgrade.button': 'Upgrade now',
    'upgrade.loading': 'Loading...',
    'upgrade.error': 'Something went wrong. Try again.',

    // DASHBOARD TOASTS
    'dashboard.workshopDeleted': 'Workshop deleted',
    'dashboard.workshopDeletedDesc': 'The workshop has been removed',
    'dashboard.deleteFailed': 'Could not delete workshop',
    'dashboard.loadFailed': 'Could not load workshops',
    'dashboard.workshopDuplicated': 'Workshop duplicated!',
    'dashboard.workshopDuplicatedDesc': 'A copy of the workshop has been created',
    'dashboard.duplicateFailed': 'Could not duplicate workshop',
    'dashboard.duplicate': 'Duplicate',
    'dashboard.showQR': 'Show QR',
    'dashboard.freePlanWarning': 'You have reached the limit of 1 workshop.',
    'dashboard.upgradeForMore': 'Upgrade to Pro',
    'dashboard.forUnlimited': 'for unlimited workshops!',
    'dashboard.workshopsMigrated': 'Your workshops are now linked to your account!',
    'dashboard.workshopsMigratedDesc': '{count} workshop(s) have been automatically linked to your new login.',
    'dashboard.checking': 'Checking your workshops...',
    'dashboard.pleaseWait': 'Please wait',
    'dashboard.takesSeconds': 'This only takes a few seconds',
    'dashboard.migrationError': 'Migration Error',
    'dashboard.tryAgain': 'Try again',

    // AI PRO BLOCKING
    'ai.proOnly': '(Pro only)',
    'ai.proRequired': 'AI analysis requires Pro',
    'ai.proRequiredDesc': 'Upgrade to Pro to unlock AI-powered analysis of your workshop results.',
    'ai.benefit1': 'AI-powered insight analysis',
    'ai.benefit2': 'Unlimited workshops',
    'ai.benefit3': 'Unlimited participants',
    'ai.upgradeNow': 'Upgrade to Pro',
    'ai.requiresProToast': 'AI analysis requires Pro subscription',

    // QR DIALOG
    'qr.title': 'Workshop QR Code',
    'qr.description': 'Share this code or QR code with your participants',
    'qr.download': 'Download QR Code',
    'qr.code': 'Workshop code',
    'qr.participantLink': 'Participant link',
    'qr.copy': 'Copy',
    'qr.copied': 'Copied!',
    'qr.copiedDesc': 'The link has been copied',

    // UPGRADE PAGE DESCRIPTIONS
    'upgrade.free.description': 'Perfect for trying Sparkboard and running occasional workshops',
    'upgrade.free.basicFeatures': 'Basic features',
    'upgrade.monthly.description': 'Full access to all features - flexible monthly subscription',
    'upgrade.yearly.description': 'Best price - full access all year for professional facilitators',
    'upgrade.pro.export': 'Export to Excel and PDF',

    // CREATE WORKSHOP PAGE UI
    'createWorkshop.backToDashboard': 'Back to Dashboard',
    'createWorkshop.badge': 'New Workshop',
    'createWorkshop.pageTitle': 'Create Workshop',
    'createWorkshop.pageSubtitle': 'Build your interactive workshop with boards and questions',
    'createWorkshop.basicInfo': 'Basic Information',
    'createWorkshop.basicInfoDesc': 'Describe your workshop',
    'createWorkshop.workshopTitleLabel': 'Workshop Title *',
    'createWorkshop.workshopTitlePlaceholder': 'E.g. Strategy Workshop 2024',
    'createWorkshop.descriptionLabel': 'Description',
    'createWorkshop.descriptionPlaceholder': 'Describe the purpose of the workshop...',
    'createWorkshop.boardsSection': 'Boards & Exercises',
    'createWorkshop.boardsSectionDesc': 'Add different exercises and questions',
    'createWorkshop.addBoardButton': 'Add Board',
    'createWorkshop.noBoardsYet': 'No boards yet',
    'createWorkshop.noBoardsStartHint': 'Start by adding your first board',
    'createWorkshop.cannotEditWithResponses': 'You cannot edit a published workshop that contains participant responses',
    'createWorkshop.saveDraftButton': 'Save as Draft',
    'createWorkshop.activateButton': 'Activate Workshop',
    'createWorkshop.tipsTitle': '💡 Tips for great workshops',
    'createWorkshop.tip1': 'Use clear and specific questions',
    'createWorkshop.tip2': 'Set realistic time limits for each board',
    'createWorkshop.tip3': 'Vary questions between reflective and creative',
    'createWorkshop.tip4': 'Color coding helps participants keep track of exercises',
    'createWorkshop.workshopCountInfo': '{count} of {limit} workshop used',
    'createWorkshop.qrDownloaded': 'QR code downloaded!',
    'createWorkshop.qrDownloadedDesc': 'The QR code has been saved as an image',

    // FACILITATOR CONTROL TOASTS
    'facilitator.workshopMissing': 'Workshop not found',
    'facilitator.workshopMissingDesc': 'Could not find the workshop. Returning to dashboard.',
    'facilitator.loadError': 'Error',
    'facilitator.loadErrorDesc': 'Could not load workshop data',
    'facilitator.timeUp': 'Time is up!',
    'facilitator.timeUpDesc': 'The board time limit has been reached',
    'facilitator.twoMinutesLeft': '2 minutes left!',
    'facilitator.twoMinutesLeftDesc': 'The board time is running out',
    'facilitator.nextBoardToast': 'Next board!',
    'facilitator.nextBoardDesc': 'Now on: {title}',
    'facilitator.switchError': 'Error',
    'facilitator.switchErrorDesc': 'Could not switch board',
    'facilitator.pdfGenerated': 'PDF generated!',
    'facilitator.pdfGeneratedDesc': 'Your workshop report has been downloaded',
    'facilitator.pdfError': 'PDF generation error',
    'facilitator.pdfErrorDesc': 'Could not create PDF. Please try again.',
    'facilitator.noteDeleted': 'Note deleted',
    'facilitator.noteDeletedDesc': 'Sticky note has been removed',
    'facilitator.deleteError': 'Error',
    'facilitator.deleteErrorDesc': 'Could not delete note',
    'facilitator.noteMoved': 'Note moved',
    'facilitator.noteMovedDesc': 'Sticky note has been moved to new category',
    'facilitator.moveError': 'Error',
    'facilitator.moveErrorDesc': 'Could not move note',
    'facilitator.participantDeleted': 'Participant removed',
    'facilitator.participantDeletedDesc': 'The participant and their notes have been removed from the workshop',
    'facilitator.participantDeleteError': 'Error',
    'facilitator.participantDeleteErrorDesc': 'Could not remove participant',
    'facilitator.participantNotesDeleteError': 'Could not delete participant notes',
    'facilitator.timerUpdateError': 'Could not update timer',
    'facilitator.showQR': 'Show QR',
    'facilitator.couldNotSwitchBoard': 'Could not switch board for participants',

    // UPGRADE REQUIRED DIALOG
    'upgradeRequired.title': 'Upgrade to Pro',
    'upgradeRequired.limitReached': 'You have reached the limit of the free plan (1 active workshop).',
    'upgradeRequired.unlockFeatures': 'Upgrade to Pro to create unlimited workshops:',
    'upgradeRequired.unlimitedWorkshops': 'Unlimited workshops',
    'upgradeRequired.unlimitedParticipants': 'Unlimited participants',
    'upgradeRequired.aiAnalysis': 'AI analysis of results',
    'upgradeRequired.prioritySupport': 'Priority support',
    'upgradeRequired.price': 'Starting at only 99 SEK/month',
    'upgradeRequired.cancel': 'Cancel',
    'upgradeRequired.seePlans': 'See plans',

    // IMPORT NOTES MOBILE TABS
    'import.selectMobile': 'Select',
    'import.methodMobile': 'Method',
    'import.aiMobile': 'AI',
    'import.previewMobile': 'Preview',
    'import.existingCategories': 'Existing categories',
    'import.newCategories': 'New categories',
    'import.existingBadge': 'Existing',
    'import.addsToBadge': 'Adds to',
    'import.newBadge': 'New',

    // PDF EXPORT
    'pdf.date': 'Date',
    'pdf.participants': 'Participants',
    'pdf.board': 'Board',
    'pdf.timeLimit': 'Time limit',
    'pdf.minutes': 'minutes',
    'pdf.question': 'Question',
    'pdf.noAnswers': 'No answers',
    'pdf.aiAnalysis': '🤖 AI Analysis',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('user_language') as Language;
    return stored || 'sv';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('user_language', lang);
  };

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language]?.[key] || key;
    
    // Replace parameters in the translation
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(`{${param}}`, value);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
